        ],
        u: "1f469-200d-2764-fe0f-200d-1f468",
        v: [
          "1f469-1f3fb-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f468-1f3ff",
        ],
        a: "2",
      },
      {
        n: [
          "man",
          "love",
          "couple",
          "couple with heart",
          "couple with heart: man, man",
        ],
        u: "1f468-200d-2764-fe0f-200d-1f468",
        v: [
          "1f468-1f3fb-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f468-1f3fb-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f468-1f3fb-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f468-1f3fb-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f468-1f3fb-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f468-1f3fc-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f468-1f3fc-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f468-1f3fc-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f468-1f3fc-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f468-1f3fc-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f468-1f3fd-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f468-1f3fd-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f468-1f3fd-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f468-1f3fd-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f468-1f3fd-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f468-1f3fe-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f468-1f3fe-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f468-1f3fe-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f468-1f3fe-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f468-1f3fe-200d-2764-fe0f-200d-1f468-1f3ff",
          "1f468-1f3ff-200d-2764-fe0f-200d-1f468-1f3fb",
          "1f468-1f3ff-200d-2764-fe0f-200d-1f468-1f3fc",
          "1f468-1f3ff-200d-2764-fe0f-200d-1f468-1f3fd",
          "1f468-1f3ff-200d-2764-fe0f-200d-1f468-1f3fe",
          "1f468-1f3ff-200d-2764-fe0f-200d-1f468-1f3ff",
        ],
        a: "2",
      },
      {
        n: [
          "love",
          "woman",
          "couple",
          "couple with heart",
          "couple with heart: woman, woman",
        ],
        u: "1f469-200d-2764-fe0f-200d-1f469",
        v: [
          "1f469-1f3fb-200d-2764-fe0f-200d-1f469-1f3fb",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f469-1f3fc",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f469-1f3fd",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f469-1f3fe",
          "1f469-1f3fb-200d-2764-fe0f-200d-1f469-1f3ff",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f469-1f3fb",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f469-1f3fc",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f469-1f3fd",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f469-1f3fe",
          "1f469-1f3fc-200d-2764-fe0f-200d-1f469-1f3ff",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f469-1f3fb",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f469-1f3fc",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f469-1f3fd",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f469-1f3fe",
          "1f469-1f3fd-200d-2764-fe0f-200d-1f469-1f3ff",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f469-1f3fb",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f469-1f3fc",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f469-1f3fd",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f469-1f3fe",
          "1f469-1f3fe-200d-2764-fe0f-200d-1f469-1f3ff",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f469-1f3fb",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f469-1f3fc",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f469-1f3fd",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f469-1f3fe",
          "1f469-1f3ff-200d-2764-fe0f-200d-1f469-1f3ff",
        ],
        a: "2",
      },
      {
        n: ["boy", "man", "woman", "family", "family: man, woman, boy"],
        u: "1f468-200d-1f469-200d-1f466",
        a: "2",
      },
      {
        n: ["man", "girl", "woman", "family", "family: man, woman, girl"],
        u: "1f468-200d-1f469-200d-1f467",
        a: "2",
      },
      {
        n: [
          "boy",
          "man",
          "girl",
          "woman",
          "family",
          "family: man, woman, girl, boy",
        ],
        u: "1f468-200d-1f469-200d-1f467-200d-1f466",
        a: "2",
      },
      {
        n: ["boy", "man", "woman", "family", "family: man, woman, boy, boy"],
        u: "1f468-200d-1f469-200d-1f466-200d-1f466",
        a: "2",
      },
      {
        n: ["man", "girl", "woman", "family", "family: man, woman, girl, girl"],
        u: "1f468-200d-1f469-200d-1f467-200d-1f467",
        a: "2",
      },
      {
        n: ["boy", "man", "family", "family: man, man, boy"],
        u: "1f468-200d-1f468-200d-1f466",
        a: "2",
      },
      {
        n: ["man", "girl", "family", "family: man, man, girl"],
        u: "1f468-200d-1f468-200d-1f467",
        a: "2",
      },
      {
        n: ["boy", "man", "girl", "family", "family: man, man, girl, boy"],
        u: "1f468-200d-1f468-200d-1f467-200d-1f466",
        a: "2",
      },
      {
        n: ["boy", "man", "family", "family: man, man, boy, boy"],
        u: "1f468-200d-1f468-200d-1f466-200d-1f466",
        a: "2",
      },
      {
        n: ["man", "girl", "family", "family: man, man, girl, girl"],
        u: "1f468-200d-1f468-200d-1f467-200d-1f467",
        a: "2",
      },
      {
        n: ["boy", "woman", "family", "family: woman, woman, boy"],
        u: "1f469-200d-1f469-200d-1f466",
        a: "2",
      },
      {
        n: ["girl", "woman", "family", "family: woman, woman, girl"],
        u: "1f469-200d-1f469-200d-1f467",
        a: "2",
      },
      {
        n: [
          "boy",
          "girl",
          "woman",
          "family",
          "family: woman, woman, girl, boy",
        ],
        u: "1f469-200d-1f469-200d-1f467-200d-1f466",
        a: "2",
      },
      {
        n: ["boy", "woman", "family", "family: woman, woman, boy, boy"],
        u: "1f469-200d-1f469-200d-1f466-200d-1f466",
        a: "2",
      },
      {
        n: ["girl", "woman", "family", "family: woman, woman, girl, girl"],
        u: "1f469-200d-1f469-200d-1f467-200d-1f467",
        a: "2",
      },
      {
        n: ["boy", "man", "family", "family: man, boy"],
        u: "1f468-200d-1f466",
        a: "4",
      },
      {
        n: ["boy", "man", "family", "family: man, boy, boy"],
        u: "1f468-200d-1f466-200d-1f466",
        a: "4",
      },
      {
        n: ["man", "girl", "family", "family: man, girl"],
        u: "1f468-200d-1f467",
        a: "4",
      },
      {
        n: ["boy", "man", "girl", "family", "family: man, girl, boy"],
        u: "1f468-200d-1f467-200d-1f466",
        a: "4",
      },
      {
        n: ["man", "girl", "family", "family: man, girl, girl"],
        u: "1f468-200d-1f467-200d-1f467",
        a: "4",
      },
      {
        n: ["boy", "woman", "family", "family: woman, boy"],
        u: "1f469-200d-1f466",
        a: "4",
      },
      {
        n: ["boy", "woman", "family", "family: woman, boy, boy"],
        u: "1f469-200d-1f466-200d-1f466",
        a: "4",
      },
      {
        n: ["girl", "woman", "family", "family: woman, girl"],
        u: "1f469-200d-1f467",
        a: "4",
      },
      {
        n: ["boy", "girl", "woman", "family", "family: woman, girl, boy"],
        u: "1f469-200d-1f467-200d-1f466",
        a: "4",
      },
      {
        n: ["girl", "woman", "family", "family: woman, girl, girl"],
        u: "1f469-200d-1f467-200d-1f467",
        a: "4",
      },
      { n: ["bust", "silhouette", "bust in silhouette"], u: "1f464", a: "0.6" },
      { n: ["bust", "silhouette", "busts in silhouette"], u: "1f465", a: "1" },
      {
        n: ["hug", "hello", "thanks", "goodbye", "people hugging"],
        u: "1fac2",
        a: "13",
      },
      { n: ["family"], u: "1f46a", a: "0.6" },
      {
        n: ["family: adult, adult, child"],
        u: "1f9d1-200d-1f9d1-200d-1f9d2",
        a: "15.1",
      },
      {
        n: ["family: adult, adult, child, child"],
        u: "1f9d1-200d-1f9d1-200d-1f9d2-200d-1f9d2",
        a: "15.1",
      },
      { n: ["family: adult, child"], u: "1f9d1-200d-1f9d2", a: "15.1" },
      {
        n: ["family: adult, child, child"],
        u: "1f9d1-200d-1f9d2-200d-1f9d2",
        a: "15.1",
      },
      {
        n: ["print", "clothing", "footprint", "footprints"],
        u: "1f463",
        a: "0.6",
      },
    ],
    animals_nature: [
      { n: ["face", "monkey", "monkey face"], u: "1f435", a: "0.6" },
      { n: ["monkey"], u: "1f412", a: "0.6" },
      { n: ["gorilla"], u: "1f98d", a: "3" },
      { n: ["ape", "orangutan"], u: "1f9a7", a: "12" },
      { n: ["dog", "pet", "face", "dog face"], u: "1f436", a: "0.6" },
      { n: ["dog", "pet"], u: "1f415", a: "0.7" },
      {
        n: ["blind", "guide", "guide dog", "accessibility"],
        u: "1f9ae",
        a: "12",
      },
      {
        n: ["dog", "service", "assistance", "service dog", "accessibility"],
        u: "1f415-200d-1f9ba",
        a: "12",
      },
      { n: ["dog", "poodle"], u: "1f429", a: "0.6" },
      { n: ["wolf", "face"], u: "1f43a", a: "0.6" },
      { n: ["fox", "face"], u: "1f98a", a: "3" },
      { n: ["sly", "raccoon", "curious"], u: "1f99d", a: "11" },
      { n: ["cat", "pet", "face", "cat face"], u: "1f431", a: "0.6" },
      { n: ["cat", "pet"], u: "1f408", a: "0.7" },
      {
        n: ["cat", "black", "unlucky", "black cat"],
        u: "1f408-200d-2b1b",
        a: "13",
      },
      { n: ["leo", "lion", "face", "zodiac"], u: "1f981", a: "1" },
      { n: ["face", "tiger", "tiger face"], u: "1f42f", a: "0.6" },
      { n: ["tiger"], u: "1f405", a: "1" },
      { n: ["leopard"], u: "1f406", a: "1" },
      { n: ["face", "horse", "horse face"], u: "1f434", a: "0.6" },
      {
        n: ["elk", "moose", "animal", "mammal", "antlers"],
        u: "1face",
        a: "15",
      },
      {
        n: ["ass", "mule", "burro", "donkey", "animal", "mammal", "stubborn"],
        u: "1facf",
        a: "15",
      },
      {
        n: ["horse", "racing", "racehorse", "equestrian"],
        u: "1f40e",
        a: "0.6",
      },
      { n: ["face", "unicorn"], u: "1f984", a: "1" },
      { n: ["zebra", "stripe"], u: "1f993", a: "5" },
      { n: ["deer"], u: "1f98c", a: "3" },
      { n: ["herd", "bison", "wisent", "buffalo"], u: "1f9ac", a: "13" },
      { n: ["cow", "face", "cow face"], u: "1f42e", a: "0.6" },
      { n: ["ox", "bull", "taurus", "zodiac"], u: "1f402", a: "1" },
      { n: ["water", "buffalo", "water buffalo"], u: "1f403", a: "1" },
      { n: ["cow"], u: "1f404", a: "1" },
      { n: ["pig", "face", "pig face"], u: "1f437", a: "0.6" },
      { n: ["pig", "sow"], u: "1f416", a: "1" },
      { n: ["pig", "boar"], u: "1f417", a: "0.6" },
      { n: ["pig", "face", "nose", "pig nose"], u: "1f43d", a: "0.6" },
      { n: ["ram", "male", "aries", "sheep", "zodiac"], u: "1f40f", a: "1" },
      { n: ["ewe", "sheep", "female"], u: "1f411", a: "0.6" },
      { n: ["goat", "zodiac", "capricorn"], u: "1f410", a: "1" },
      { n: ["hump", "camel", "dromedary"], u: "1f42a", a: "1" },
      {
        n: ["hump", "camel", "bactrian", "two hump camel"],
        u: "1f42b",
        a: "0.6",
      },
      {
        n: ["wool", "llama", "alpaca", "vicuña", "guanaco"],
        u: "1f999",
        a: "11",
      },
      { n: ["spots", "giraffe"], u: "1f992", a: "5" },
      { n: ["elephant"], u: "1f418", a: "0.6" },
      {
        n: ["tusk", "large", "woolly", "mammoth", "extinction"],
        u: "1f9a3",
        a: "13",
      },
      { n: ["rhinoceros"], u: "1f98f", a: "3" },
      { n: ["hippo", "hippopotamus"], u: "1f99b", a: "11" },
      { n: ["face", "mouse", "mouse face"], u: "1f42d", a: "0.6" },
      { n: ["mouse"], u: "1f401", a: "1" },
      { n: ["rat"], u: "1f400", a: "1" },
      { n: ["pet", "face", "hamster"], u: "1f439", a: "0.6" },
      {
        n: ["pet", "face", "bunny", "rabbit", "rabbit face"],
        u: "1f430",
        a: "0.6",
      },
      { n: ["pet", "bunny", "rabbit"], u: "1f407", a: "1" },
      { n: ["dam", "beaver"], u: "1f9ab", a: "13" },
      { n: ["spiny", "hedgehog"], u: "1f994", a: "5" },
      { n: ["bat", "vampire"], u: "1f987", a: "3" },
      { n: ["bear", "face"], u: "1f43b", a: "0.6" },
      {
        n: ["bear", "white", "arctic", "polar bear"],
        u: "1f43b-200d-2744-fe0f",
        a: "13",
      },
      { n: ["face", "koala", "marsupial"], u: "1f428", a: "0.6" },
      { n: ["face", "panda"], u: "1f43c", a: "0.6" },
      { n: ["lazy", "slow", "sloth"], u: "1f9a5", a: "12" },
      { n: ["otter", "fishing", "playful"], u: "1f9a6", a: "12" },
      { n: ["skunk", "stink"], u: "1f9a8", a: "12" },
      { n: ["joey", "jump", "kangaroo", "marsupial"], u: "1f998", a: "11" },
      { n: ["badger", "pester", "honey badger"], u: "1f9a1", a: "11" },
      { n: ["paw", "feet", "print", "paw prints"], u: "1f43e", a: "0.6" },
      { n: ["bird", "turkey"], u: "1f983", a: "1" },
      { n: ["bird", "chicken"], u: "1f414", a: "0.6" },
      { n: ["bird", "rooster"], u: "1f413", a: "1" },
      {
        n: ["baby", "bird", "chick", "hatching", "hatching chick"],
        u: "1f423",
        a: "0.6",
      },
      { n: ["baby", "bird", "chick", "baby chick"], u: "1f424", a: "0.6" },
      {
        n: ["baby", "bird", "chick", "front facing baby chick"],
        u: "1f425",
        a: "0.6",
      },
      { n: ["bird"], u: "1f426", a: "0.6" },
      { n: ["bird", "penguin"], u: "1f427", a: "0.6" },
      { n: ["bird", "eagle"], u: "1f985", a: "3" },
      { n: ["duck", "bird"], u: "1f986", a: "3" },
      { n: ["swan", "bird", "cygnet", "ugly duckling"], u: "1f9a2", a: "11" },
      { n: ["owl", "bird", "wise"], u: "1f989", a: "3" },
      { n: ["dodo", "large", "mauritius", "extinction"], u: "1f9a4", a: "13" },
      {
        n: ["bird", "light", "flight", "feather", "plumage"],
        u: "1fab6",
        a: "13",
      },
      { n: ["flamingo", "tropical", "flamboyant"], u: "1f9a9", a: "12" },
      {
        n: ["bird", "proud", "peahen", "peacock", "ostentatious"],
        u: "1f99a",
        a: "11",
      },
      { n: ["bird", "talk", "parrot", "pirate"], u: "1f99c", a: "11" },
      {
        n: ["wing", "bird", "flying", "angelic", "aviation", "mythology"],
        u: "1fabd",
        a: "15",
      },
      {
        n: ["bird", "crow", "rook", "black", "raven", "black bird"],
        u: "1f426-200d-2b1b",
        a: "15",
      },
      { n: ["bird", "fowl", "honk", "goose", "silly"], u: "1fabf", a: "15" },
      {
        n: ["phoenix", "fantasy", "rebirth", "firebird", "reincarnation"],
        u: "1f426-200d-1f525",
        a: "15.1",
      },
      { n: ["frog", "face"], u: "1f438", a: "0.6" },
      { n: ["crocodile"], u: "1f40a", a: "1" },
      { n: ["turtle", "terrapin", "tortoise"], u: "1f422", a: "0.6" },
      { n: ["lizard", "reptile"], u: "1f98e", a: "3" },
      {
        n: ["snake", "bearer", "zodiac", "serpent", "ophiuchus"],
        u: "1f40d",
        a: "0.6",
      },
      {
        n: ["face", "dragon", "fairy tale", "dragon face"],
        u: "1f432",
        a: "0.6",
      },
      { n: ["dragon", "fairy tale"], u: "1f409", a: "1" },
      {
        n: ["sauropod", "diplodocus", "brontosaurus", "brachiosaurus"],
        u: "1f995",
        a: "5",
      },
      { n: ["T Rex", "t rex", "tyrannosaurus rex"], u: "1f996", a: "5" },
      {
        n: ["face", "whale", "spouting", "spouting whale"],
        u: "1f433",
        a: "0.6",
      },
      { n: ["whale"], u: "1f40b", a: "1" },
      { n: ["dolphin", "flipper"], u: "1f42c", a: "0.6" },
      { n: ["seal", "sea lion"], u: "1f9ad", a: "13" },
      { n: ["fish", "pisces", "zodiac"], u: "1f41f", a: "0.6" },
      { n: ["fish", "tropical", "tropical fish"], u: "1f420", a: "0.6" },
      { n: ["fish", "blowfish"], u: "1f421", a: "0.6" },
      { n: ["fish", "shark"], u: "1f988", a: "3" },
      { n: ["octopus"], u: "1f419", a: "0.6" },
      { n: ["shell", "spiral", "spiral shell"], u: "1f41a", a: "0.6" },
      { n: ["reef", "coral", "ocean"], u: "1fab8", a: "14" },
      {
        n: [
          "burn",
          "ouch",
          "jelly",
          "marine",
          "stinger",
          "jellyfish",
          "invertebrate",
        ],
        u: "1fabc",
        a: "15",
      },
      { n: ["snail"], u: "1f40c", a: "0.6" },
      { n: ["insect", "pretty", "butterfly"], u: "1f98b", a: "3" },
      { n: ["bug", "insect"], u: "1f41b", a: "0.6" },
      { n: ["ant", "insect"], u: "1f41c", a: "0.6" },
      { n: ["bee", "insect", "honeybee"], u: "1f41d", a: "0.6" },
      { n: ["bug", "beetle", "insect"], u: "1fab2", a: "13" },
      {
        n: ["beetle", "insect", "ladybug", "ladybird", "lady beetle"],
        u: "1f41e",
        a: "0.6",
      },
      { n: ["cricket", "grasshopper"], u: "1f997", a: "5" },
      { n: ["pest", "roach", "insect", "cockroach"], u: "1fab3", a: "13" },
      { n: ["zodiac", "scorpio", "scorpion"], u: "1f982", a: "1" },
      {
        n: ["pest", "fever", "virus", "disease", "malaria", "mosquito"],
        u: "1f99f",
        a: "11",
      },
      {
        n: ["fly", "pest", "maggot", "disease", "rotting"],
        u: "1fab0",
        a: "13",
      },
      { n: ["worm", "annelid", "parasite", "earthworm"], u: "1fab1", a: "13" },
      { n: ["virus", "amoeba", "microbe", "bacteria"], u: "1f9a0", a: "11" },
      { n: ["flower", "bouquet"], u: "1f490", a: "0.6" },
      {
        n: ["cherry", "flower", "blossom", "cherry blossom"],
        u: "1f338",
        a: "0.6",
      },
      { n: ["flower", "white flower"], u: "1f4ae", a: "0.6" },
      {
        n: ["lotus", "flower", "purity", "buddhism", "hinduism"],
        u: "1fab7",
        a: "14",
      },
      { n: ["rose", "flower"], u: "1f339", a: "0.6" },
      { n: ["flower", "wilted", "wilted flower"], u: "1f940", a: "3" },
      { n: ["flower", "hibiscus"], u: "1f33a", a: "0.6" },
      { n: ["sun", "flower", "sunflower"], u: "1f33b", a: "0.6" },
      { n: ["flower", "blossom"], u: "1f33c", a: "0.6" },
      { n: ["tulip", "flower"], u: "1f337", a: "0.6" },
      {
        n: [
          "flower",
          "lupine",
          "hyacinth",
          "lavender",
          "bluebonnet",
          "snapdragon",
        ],
        u: "1fabb",
        a: "15",
      },
      { n: ["young", "seedling"], u: "1f331", a: "0.6" },
      {
        n: [
          "grow",
          "house",
          "plant",
          "boring",
          "useless",
          "nurturing",
          "potted plant",
        ],
        u: "1fab4",
        a: "13",
      },
      { n: ["tree", "evergreen tree"], u: "1f332", a: "1" },
      {
        n: ["tree", "shedding", "deciduous", "deciduous tree"],
        u: "1f333",
        a: "1",
      },
      { n: ["palm", "tree", "palm tree"], u: "1f334", a: "0.6" },
      { n: ["plant", "cactus"], u: "1f335", a: "0.6" },
      { n: ["ear", "rice", "grain", "sheaf of rice"], u: "1f33e", a: "0.6" },
      { n: ["herb", "leaf"], u: "1f33f", a: "0.6" },
      {
        n: ["4", "four", "leaf", "clover", "four leaf clover"],
        u: "1f340",
        a: "0.6",
      },
      { n: ["leaf", "maple", "falling", "maple leaf"], u: "1f341", a: "0.6" },
      { n: ["leaf", "falling", "fallen leaf"], u: "1f342", a: "0.6" },
      {
        n: ["blow", "leaf", "wind", "flutter", "leaf fluttering in wind"],
        u: "1f343",
        a: "0.6",
      },
      { n: ["nesting", "empty nest"], u: "1fab9", a: "14" },
      { n: ["nesting", "nest with eggs"], u: "1faba", a: "14" },
      { n: ["mushroom", "toadstool"], u: "1f344", a: "0.6" },
    ],
    food_drink: [
      { n: ["fruit", "grape", "grapes"], u: "1f347", a: "0.6" },
      { n: ["melon", "fruit"], u: "1f348", a: "0.6" },
      { n: ["fruit", "watermelon"], u: "1f349", a: "0.6" },
      { n: ["fruit", "orange", "tangerine"], u: "1f34a", a: "0.6" },
      { n: ["lemon", "fruit", "citrus"], u: "1f34b", a: "1" },
      {
        n: ["lime", "fruit", "citrus", "tropical"],
        u: "1f34b-200d-1f7e9",
        a: "15.1",
      },
      { n: ["fruit", "banana"], u: "1f34c", a: "0.6" },
      { n: ["fruit", "pineapple"], u: "1f34d", a: "0.6" },
      { n: ["mango", "fruit", "tropical"], u: "1f96d", a: "11" },
      { n: ["red", "apple", "fruit", "red apple"], u: "1f34e", a: "0.6" },
      { n: ["apple", "fruit", "green", "green apple"], u: "1f34f", a: "0.6" },
      { n: ["pear", "fruit"], u: "1f350", a: "1" },
      { n: ["peach", "fruit"], u: "1f351", a: "0.6" },
      {
        n: ["red", "fruit", "cherry", "berries", "cherries"],
        u: "1f352",
        a: "0.6",
      },
      { n: ["berry", "fruit", "strawberry"], u: "1f353", a: "0.6" },
      {
        n: ["blue", "berry", "bilberry", "blueberry", "blueberries"],
        u: "1fad0",
        a: "13",
      },
      { n: ["food", "kiwi", "fruit", "kiwi fruit"], u: "1f95d", a: "3" },
      { n: ["fruit", "tomato", "vegetable"], u: "1f345", a: "0.6" },
      { n: ["food", "olive"], u: "1fad2", a: "13" },
      { n: ["palm", "coconut", "piña colada"], u: "1f965", a: "5" },
      { n: ["food", "fruit", "avocado"], u: "1f951", a: "3" },
      { n: ["eggplant", "aubergine", "vegetable"], u: "1f346", a: "0.6" },
      { n: ["food", "potato", "vegetable"], u: "1f954", a: "3" },
      { n: ["food", "carrot", "vegetable"], u: "1f955", a: "3" },
      {
        n: ["ear", "corn", "maze", "maize", "ear of corn"],
        u: "1f33d",
        a: "0.6",
      },
      {
        n: ["pepper", "capsicum", "vegetable", "bell pepper"],
        u: "1fad1",
        a: "13",
      },
      { n: ["food", "pickle", "cucumber", "vegetable"], u: "1f952", a: "3" },
      {
        n: ["kale", "cabbage", "lettuce", "bok choy", "leafy green"],
        u: "1f96c",
        a: "11",
      },
      { n: ["broccoli", "wild cabbage"], u: "1f966", a: "5" },
      { n: ["garlic", "flavoring"], u: "1f9c4", a: "12" },
      { n: ["onion", "flavoring"], u: "1f9c5", a: "12" },
      {
        n: ["nut", "food", "peanut", "peanuts", "vegetable"],
        u: "1f95c",
        a: "3",
      },
      { n: ["food", "beans", "kidney", "legume"], u: "1fad8", a: "14" },
      { n: ["plant", "chestnut"], u: "1f330", a: "0.6" },
      { n: ["beer", "root", "spice", "ginger root"], u: "1fada", a: "15" },
      {
        n: ["pea", "pod", "beans", "legume", "pea pod", "edamame", "vegetable"],
        u: "1fadb",
        a: "15",
      },
      {
        n: ["food", "fungus", "nature", "vegetable", "brown mushroom"],
        u: "1f344-200d-1f7eb",
        a: "15.1",
      },
      { n: ["loaf", "bread"], u: "1f35e", a: "0.6" },
      {
        n: ["food", "roll", "bread", "french", "croissant", "breakfast"],
        u: "1f950",
        a: "3",
      },
      {
        n: ["food", "bread", "french", "baguette", "baguette bread"],
        u: "1f956",
        a: "3",
      },
      {
        n: ["naan", "pita", "arepa", "lavash", "flatbread"],
        u: "1fad3",
        a: "13",
      },
      { n: ["pretzel", "twisted"], u: "1f968", a: "5" },
      { n: ["bagel", "bakery", "schmear", "breakfast"], u: "1f96f", a: "11" },
      {
        n: ["food", "crêpe", "hotcake", "pancake", "pancakes", "breakfast"],
        u: "1f95e",
        a: "3",
      },
      { n: ["iron", "waffle", "breakfast", "indecisive"], u: "1f9c7", a: "12" },
      { n: ["cheese", "cheese wedge"], u: "1f9c0", a: "1" },
      { n: ["bone", "meat", "meat on bone"], u: "1f356", a: "0.6" },
      {
        n: ["leg", "bone", "chicken", "poultry", "drumstick", "poultry leg"],
        u: "1f357",
        a: "0.6",
      },
      {
        n: ["chop", "steak", "lambchop", "porkchop", "cut of meat"],
        u: "1f969",
        a: "5",
      },
      { n: ["food", "meat", "bacon", "breakfast"], u: "1f953", a: "3" },
      { n: ["burger", "hamburger"], u: "1f354", a: "0.6" },
      { n: ["fries", "french", "french fries"], u: "1f35f", a: "0.6" },
      { n: ["pizza", "slice", "cheese"], u: "1f355", a: "0.6" },
      {
        n: ["hotdog", "hot dog", "sausage", "frankfurter"],
        u: "1f32d",
        a: "1",
      },
      { n: ["bread", "sandwich"], u: "1f96a", a: "5" },
      { n: ["taco", "mexican"], u: "1f32e", a: "1" },
      { n: ["wrap", "burrito", "mexican"], u: "1f32f", a: "1" },
      { n: ["tamale", "mexican", "wrapped"], u: "1fad4", a: "13" },
      {
        n: [
          "food",
          "gyro",
          "kebab",
          "falafel",
          "stuffed",
          "flatbread",
          "stuffed flatbread",
        ],
        u: "1f959",
        a: "3",
      },
      { n: ["falafel", "chickpea", "meatball"], u: "1f9c6", a: "12" },
      { n: ["egg", "food", "breakfast"], u: "1f95a", a: "3" },
      {
        n: ["egg", "pan", "frying", "cooking", "breakfast"],
        u: "1f373",
        a: "0.6",
      },
      {
        n: [
          "pan",
          "food",
          "paella",
          "shallow",
          "casserole",
          "shallow pan of food",
        ],
        u: "1f958",
        a: "3",
      },
      { n: ["pot", "stew", "pot of food"], u: "1f372", a: "0.6" },
      {
        n: ["pot", "swiss", "fondue", "cheese", "melted", "chocolate"],
        u: "1fad5",
        a: "13",
      },
      {
        n: ["cereal", "congee", "breakfast", "bowl with spoon"],
        u: "1f963",
        a: "5",
      },
      { n: ["food", "green", "salad", "green salad"], u: "1f957", a: "3" },
      { n: ["popcorn"], u: "1f37f", a: "1" },
      { n: ["dairy", "butter"], u: "1f9c8", a: "12" },
      { n: ["salt", "shaker", "condiment"], u: "1f9c2", a: "11" },
      { n: ["can", "canned food"], u: "1f96b", a: "5" },
      { n: ["box", "bento", "bento box"], u: "1f371", a: "0.6" },
      { n: ["rice", "cracker", "rice cracker"], u: "1f358", a: "0.6" },
      { n: ["ball", "rice", "japanese", "rice ball"], u: "1f359", a: "0.6" },
      { n: ["rice", "cooked", "cooked rice"], u: "1f35a", a: "0.6" },
      { n: ["rice", "curry", "curry rice"], u: "1f35b", a: "0.6" },
      {
        n: ["bowl", "ramen", "noodle", "steaming", "steaming bowl"],
        u: "1f35c",
        a: "0.6",
      },
      { n: ["pasta", "spaghetti"], u: "1f35d", a: "0.6" },
      {
        n: ["sweet", "potato", "roasted", "roasted sweet potato"],
        u: "1f360",
        a: "0.6",
      },
      {
        n: ["oden", "kebab", "stick", "skewer", "seafood"],
        u: "1f362",
        a: "0.6",
      },
      { n: ["sushi"], u: "1f363", a: "0.6" },
      {
        n: ["fried", "prawn", "shrimp", "tempura", "fried shrimp"],
        u: "1f364",
        a: "0.6",
      },
      {
        n: ["cake", "fish", "swirl", "pastry", "fish cake with swirl"],
        u: "1f365",
        a: "0.6",
      },
      {
        n: ["autumn", "yuèbǐng", "festival", "moon cake"],
        u: "1f96e",
        a: "11",
      },
      {
        n: ["dango", "stick", "sweet", "skewer", "dessert", "japanese"],
        u: "1f361",
        a: "0.6",
      },
      {
        n: ["gyōza", "jiaozi", "pierogi", "dumpling", "empanada", "potsticker"],
        u: "1f95f",
        a: "5",
      },
      { n: ["prophecy", "fortune cookie"], u: "1f960", a: "5" },
      { n: ["takeout box", "oyster pail"], u: "1f961", a: "5" },
      { n: ["crab", "cancer", "zodiac"], u: "1f980", a: "1" },
      { n: ["claws", "bisque", "lobster", "seafood"], u: "1f99e", a: "11" },
      { n: ["food", "small", "shrimp", "shellfish"], u: "1f990", a: "3" },
      { n: ["food", "squid", "molusc"], u: "1f991", a: "3" },
      { n: ["pearl", "oyster", "diving"], u: "1f9aa", a: "12" },
      {
        n: [
          "ice",
          "soft",
          "cream",
          "sweet",
          "dessert",
          "icecream",
          "soft ice cream",
        ],
        u: "1f366",
        a: "0.6",
      },
      {
        n: ["ice", "sweet", "shaved", "dessert", "shaved ice"],
        u: "1f367",
        a: "0.6",
      },
      {
        n: ["ice", "cream", "sweet", "dessert", "ice cream"],
        u: "1f368",
        a: "0.6",
      },
      {
        n: ["donut", "sweet", "dessert", "doughnut", "breakfast"],
        u: "1f369",
        a: "0.6",
      },
      { n: ["sweet", "cookie", "dessert"], u: "1f36a", a: "0.6" },
      {
        n: [
          "cake",
          "sweet",
          "pastry",
          "dessert",
          "birthday",
          "celebration",
          "birthday cake",
        ],
        u: "1f382",
        a: "0.6",
      },
      {
        n: ["cake", "slice", "sweet", "pastry", "dessert", "shortcake"],
        u: "1f370",
        a: "0.6",
      },
      { n: ["sweet", "bakery", "cupcake"], u: "1f9c1", a: "11" },
      { n: ["pie", "pastry", "filling"], u: "1f967", a: "5" },
      {
        n: ["bar", "sweet", "dessert", "chocolate", "chocolate bar"],
        u: "1f36b",
        a: "0.6",
      },
      { n: ["candy", "sweet", "dessert"], u: "1f36c", a: "0.6" },
      { n: ["candy", "sweet", "dessert", "lollipop"], u: "1f36d", a: "0.6" },
      { n: ["sweet", "custard", "dessert", "pudding"], u: "1f36e", a: "0.6" },
      {
        n: ["pot", "honey", "sweet", "honeypot", "honey pot"],
        u: "1f36f",
        a: "0.6",
      },
      {
        n: ["baby", "milk", "drink", "bottle", "baby bottle"],
        u: "1f37c",
        a: "1",
      },
      { n: ["milk", "drink", "glass", "glass of milk"], u: "1f95b", a: "3" },
      {
        n: [
          "hot",
          "tea",
          "drink",
          "coffee",
          "beverage",
          "steaming",
          "hot beverage",
        ],
        u: "2615",
        a: "0.6",
      },
      { n: ["pot", "tea", "drink", "teapot"], u: "1fad6", a: "13" },
      {
        n: [
          "cup",
          "tea",
          "drink",
          "teacup",
          "beverage",
          "teacup without handle",
        ],
        u: "1f375",
        a: "0.6",
      },
      {
        n: ["bar", "cup", "sake", "drink", "bottle", "beverage"],
        u: "1f376",
        a: "0.6",
      },
      {
        n: [
          "bar",
          "cork",
          "drink",
          "bottle",
          "popping",
          "bottle with popping cork",
        ],
        u: "1f37e",
        a: "1",
      },
      {
        n: ["bar", "wine", "drink", "glass", "beverage", "wine glass"],
        u: "1f377",
        a: "0.6",
      },
      {
        n: ["bar", "drink", "glass", "cocktail", "cocktail glass"],
        u: "1f378",
        a: "0.6",
      },
      {
        n: ["bar", "drink", "tropical", "tropical drink"],
        u: "1f379",
        a: "0.6",
      },
      { n: ["bar", "mug", "beer", "drink", "beer mug"], u: "1f37a", a: "0.6" },
      {
        n: ["bar", "mug", "beer", "clink", "drink", "clinking beer mugs"],
        u: "1f37b",
        a: "0.6",
      },
      {
        n: ["clink", "drink", "glass", "celebrate", "clinking glasses"],
        u: "1f942",
        a: "3",
      },
      {
        n: ["shot", "glass", "liquor", "whisky", "tumbler", "tumbler glass"],
        u: "1f943",
        a: "3",
      },
      {
        n: ["drink", "empty", "glass", "spill", "pouring liquid"],
        u: "1fad7",
        a: "14",
      },
      { n: ["soda", "juice", "cup with straw"], u: "1f964", a: "5" },
      {
        n: ["tea", "milk", "pearl", "bubble", "bubble tea"],
        u: "1f9cb",
        a: "13",
      },
      {
        n: ["box", "juice", "straw", "sweet", "beverage", "beverage box"],
        u: "1f9c3",
        a: "12",
      },
      { n: ["mate", "drink"], u: "1f9c9", a: "12" },
      { n: ["ice", "cold", "iceberg", "ice cube"], u: "1f9ca", a: "12" },
      { n: ["hashi", "chopsticks"], u: "1f962", a: "5" },
      {
        n: ["fork", "knife", "cooking", "cutlery", "fork and knife"],
        u: "1f374",
        a: "0.6",
      },
      { n: ["spoon", "tableware"], u: "1f944", a: "3" },
      {
        n: ["tool", "hocho", "knife", "weapon", "cooking", "kitchen knife"],
        u: "1f52a",
        a: "0.6",
      },
      {
        n: ["jar", "empty", "sauce", "store", "condiment", "container"],
        u: "1fad9",
        a: "14",
      },
      {
        n: ["jug", "drink", "zodiac", "amphora", "cooking", "aquarius"],
        u: "1f3fa",
        a: "1",
      },
    ],
    travel_places: [
      {
        n: [
          "earth",
          "globe",
          "world",
          "africa",
          "europe",
          "globe showing Europe Africa",
          "globe showing europe africa",
        ],
        u: "1f30d",
        a: "0.7",
      },
      {
        n: [
          "earth",
          "globe",
          "world",
          "americas",
          "globe showing Americas",
          "globe showing americas",
        ],
        u: "1f30e",
        a: "0.7",
      },
      {
        n: [
          "asia",
          "earth",
          "globe",
          "world",
          "australia",
          "globe showing Asia Australia",
          "globe showing asia australia",
        ],
        u: "1f30f",
        a: "0.6",
      },
      {
        n: ["earth", "globe", "world", "meridians", "globe with meridians"],
        u: "1f310",
        a: "1",
      },
      {
        n: ["map", "japan", "map of Japan", "map of japan"],
        u: "1f5fe",
        a: "0.6",
      },
      {
        n: ["compass", "magnetic", "navigation", "orienteering"],
        u: "1f9ed",
        a: "11",
      },
      { n: ["volcano", "eruption", "mountain"], u: "1f30b", a: "0.6" },
      { n: ["fuji", "mountain", "mount fuji"], u: "1f5fb", a: "0.6" },
      { n: ["clay", "wall", "brick", "bricks", "mortar"], u: "1f9f1", a: "11" },
      {
        n: ["rock", "heavy", "solid", "stone", "boulder"],
        u: "1faa8",
        a: "13",
      },
      { n: ["log", "wood", "lumber", "timber"], u: "1fab5", a: "13" },
      { n: ["hut", "yurt", "house", "roundhouse"], u: "1f6d6", a: "13" },
      { n: ["home", "house"], u: "1f3e0", a: "0.6" },
      {
        n: ["home", "house", "garden", "house with garden"],
        u: "1f3e1",
        a: "0.6",
      },
      { n: ["building", "office building"], u: "1f3e2", a: "0.6" },
      {
        n: ["post", "japanese", "Japanese post office", "japanese post office"],
        u: "1f3e3",
        a: "0.6",
      },
      { n: ["post", "european", "post office"], u: "1f3e4", a: "1" },
      { n: ["doctor", "hospital", "medicine"], u: "1f3e5", a: "0.6" },
      { n: ["bank", "building"], u: "1f3e6", a: "0.6" },
      { n: ["hotel", "building"], u: "1f3e8", a: "0.6" },
      { n: ["love", "hotel", "love hotel"], u: "1f3e9", a: "0.6" },
      {
        n: ["store", "convenience", "convenience store"],
        u: "1f3ea",
        a: "0.6",
      },
      { n: ["school", "building"], u: "1f3eb", a: "0.6" },
      { n: ["store", "department", "department store"], u: "1f3ec", a: "0.6" },
      { n: ["factory", "building"], u: "1f3ed", a: "0.6" },
      { n: ["castle", "japanese", "Japanese castle"], u: "1f3ef", a: "0.6" },
      { n: ["castle", "european"], u: "1f3f0", a: "0.6" },
      { n: ["chapel", "wedding", "romance"], u: "1f492", a: "0.6" },
      { n: ["tokyo", "tower", "Tokyo tower"], u: "1f5fc", a: "0.6" },
      {
        n: ["statue", "liberty", "Statue of Liberty", "statue of liberty"],
        u: "1f5fd",
        a: "0.6",
      },
      { n: ["cross", "church", "religion", "christian"], u: "26ea", a: "0.6" },
      { n: ["islam", "mosque", "muslim", "religion"], u: "1f54c", a: "1" },
      { n: ["hindu", "temple", "hindu temple"], u: "1f6d5", a: "12" },
      {
        n: ["jew", "jewish", "temple", "religion", "synagogue"],
        u: "1f54d",
        a: "1",
      },
      { n: ["kaaba", "islam", "muslim", "religion"], u: "1f54b", a: "1" },
      { n: ["fountain"], u: "26f2", a: "0.6" },
      { n: ["tent", "camping"], u: "26fa", a: "0.6" },
      { n: ["fog", "foggy"], u: "1f301", a: "0.6" },
      { n: ["star", "night", "night with stars"], u: "1f303", a: "0.6" },
      {
        n: ["sun", "morning", "sunrise", "mountain", "sunrise over mountains"],
        u: "1f304",
        a: "0.6",
      },
      { n: ["sun", "sunrise", "morning"], u: "1f305", a: "0.6" },
      {
        n: [
          "city",
          "dusk",
          "sunset",
          "evening",
          "landscape",
          "cityscape at dusk",
        ],
        u: "1f306",
        a: "0.6",
      },
      { n: ["sun", "dusk", "sunset"], u: "1f307", a: "0.6" },
      { n: ["night", "bridge", "bridge at night"], u: "1f309", a: "0.6" },
      { n: ["horse", "carousel", "carousel horse"], u: "1f3a0", a: "0.6" },
      {
        n: ["play", "theme park", "amusement park", "playground slide"],
        u: "1f6dd",
        a: "14",
      },
      {
        n: ["wheel", "ferris", "theme park", "ferris wheel", "amusement park"],
        u: "1f3a1",
        a: "0.6",
      },
      {
        n: [
          "roller",
          "coaster",
          "theme park",
          "roller coaster",
          "amusement park",
        ],
        u: "1f3a2",
        a: "0.6",
      },
      { n: ["pole", "barber", "haircut", "barber pole"], u: "1f488", a: "0.6" },
      { n: ["tent", "circus", "circus tent"], u: "1f3aa", a: "0.6" },
      {
        n: ["steam", "train", "engine", "railway", "locomotive"],
        u: "1f682",
        a: "1",
      },
      {
        n: [
          "car",
          "tram",
          "train",
          "railway",
          "electric",
          "trolleybus",
          "railway car",
        ],
        u: "1f683",
        a: "0.6",
      },
      {
        n: ["speed", "train", "railway", "shinkansen", "high speed train"],
        u: "1f684",
        a: "0.6",
      },
      {
        n: [
          "speed",
          "train",
          "bullet",
          "railway",
          "shinkansen",
          "bullet train",
        ],
        u: "1f685",
        a: "0.6",
      },
      { n: ["train", "railway"], u: "1f686", a: "1" },
      { n: ["metro", "subway"], u: "1f687", a: "0.6" },
      { n: ["railway", "light rail"], u: "1f688", a: "1" },
      { n: ["train", "station", "railway"], u: "1f689", a: "0.6" },
      { n: ["tram", "trolleybus"], u: "1f68a", a: "1" },
      { n: ["vehicle", "monorail"], u: "1f69d", a: "1" },
      {
        n: ["car", "railway", "mountain", "mountain railway"],
        u: "1f69e",
        a: "1",
      },
      { n: ["car", "tram", "tram car", "trolleybus"], u: "1f68b", a: "1" },
      { n: ["bus", "vehicle"], u: "1f68c", a: "0.6" },
      { n: ["bus", "oncoming", "oncoming bus"], u: "1f68d", a: "0.7" },
      { n: ["bus", "tram", "trolley", "trolleybus"], u: "1f68e", a: "1" },
      { n: ["bus", "minibus"], u: "1f690", a: "1" },
      { n: ["vehicle", "ambulance"], u: "1f691", a: "0.6" },
      { n: ["fire", "truck", "engine", "fire engine"], u: "1f692", a: "0.6" },
      { n: ["car", "patrol", "police", "police car"], u: "1f693", a: "0.6" },
      {
        n: ["car", "police", "oncoming", "oncoming police car"],
        u: "1f694",
        a: "0.7",
      },
      { n: ["taxi", "vehicle"], u: "1f695", a: "0.6" },
      { n: ["taxi", "oncoming", "oncoming taxi"], u: "1f696", a: "1" },
      { n: ["car", "automobile"], u: "1f697", a: "0.6" },
      {
        n: ["car", "oncoming", "automobile", "oncoming automobile"],
        u: "1f698",
        a: "0.7",
      },
      {
        n: ["recreational", "sport utility", "sport utility vehicle"],
        u: "1f699",
        a: "0.6",
      },
      {
        n: ["truck", "pickup", "pick up", "pickup truck"],
        u: "1f6fb",
        a: "13",
      },
      { n: ["truck", "delivery", "delivery truck"], u: "1f69a", a: "0.6" },
      {
        n: ["semi", "lorry", "truck", "articulated lorry"],
        u: "1f69b",
        a: "1",
      },
      { n: ["tractor", "vehicle"], u: "1f69c", a: "1" },
      { n: ["motor", "scooter", "motor scooter"], u: "1f6f5", a: "3" },
      { n: ["accessibility", "manual wheelchair"], u: "1f9bd", a: "12" },
      { n: ["accessibility", "motorized wheelchair"], u: "1f9bc", a: "12" },
      { n: ["tuk tuk", "auto rickshaw"], u: "1f6fa", a: "12" },
      { n: ["bike", "bicycle"], u: "1f6b2", a: "0.6" },
      { n: ["kick", "scooter", "kick scooter"], u: "1f6f4", a: "3" },
      { n: ["board", "skateboard"], u: "1f6f9", a: "11" },
      { n: ["skate", "roller", "roller skate"], u: "1f6fc", a: "13" },
      { n: ["bus", "stop", "bus stop"], u: "1f68f", a: "0.6" },
      {
        n: [
          "gas",
          "fuel",
          "pump",
          "diesel",
          "station",
          "fuelpump",
          "fuel pump",
        ],
        u: "26fd",
        a: "0.6",
      },
      { n: ["tire", "turn", "wheel", "circle"], u: "1f6de", a: "14" },
      {
        n: [
          "car",
          "light",
          "beacon",
          "police",
          "revolving",
          "police car light",
        ],
        u: "1f6a8",
        a: "0.6",
      },
      {
        n: ["light", "signal", "traffic", "horizontal traffic light"],
        u: "1f6a5",
        a: "0.6",
      },
      {
        n: ["light", "signal", "traffic", "vertical traffic light"],
        u: "1f6a6",
        a: "1",
      },
      { n: ["sign", "stop", "stop sign", "octagonal"], u: "1f6d1", a: "3" },
      { n: ["barrier", "construction"], u: "1f6a7", a: "0.6" },
      { n: ["ship", "tool", "anchor"], u: "2693", a: "0.6" },
      {
        n: [
          "float",
          "rescue",
          "safety",
          "ring buoy",
          "life saver",
          "life preserver",
        ],
        u: "1f6df",
        a: "14",
      },
      {
        n: ["sea", "boat", "yacht", "resort", "sailboat"],
        u: "26f5",
        a: "0.6",
      },
      { n: ["boat", "canoe"], u: "1f6f6", a: "3" },
      { n: ["boat", "speedboat"], u: "1f6a4", a: "0.6" },
      { n: ["ship", "boat", "passenger"], u: "1f6a2", a: "0.6" },
      {
        n: [
          "airplane",
          "check in",
          "aeroplane",
          "departure",
          "departures",
          "airplane departure",
        ],
        u: "1f6eb",
        a: "1",
      },
      {
        n: [
          "landing",
          "airplane",
          "arrivals",
          "arriving",
          "aeroplane",
          "airplane arrival",
        ],
        u: "1f6ec",
        a: "1",
      },
      {
        n: ["skydive", "parasail", "parachute", "hang glide"],
        u: "1fa82",
        a: "12",
      },
      { n: ["seat", "chair"], u: "1f4ba", a: "0.6" },
      { n: ["vehicle", "helicopter"], u: "1f681", a: "1" },
      {
        n: ["railway", "suspension", "suspension railway"],
        u: "1f69f",
        a: "1",
      },
      {
        n: ["cable", "gondola", "mountain", "mountain cableway"],
        u: "1f6a0",
        a: "1",
      },
      {
        n: ["car", "cable", "aerial", "gondola", "tramway", "aerial tramway"],
        u: "1f6a1",
        a: "1",
      },
      { n: ["space", "rocket"], u: "1f680", a: "0.6" },
      { n: ["ufo", "flying saucer"], u: "1f6f8", a: "5" },
      { n: ["travel", "luggage", "packing"], u: "1f9f3", a: "11" },
      { n: ["sand", "timer", "hourglass done"], u: "231b", a: "0.6" },
      {
        n: ["sand", "timer", "hourglass", "hourglass not done"],
        u: "23f3",
        a: "0.6",
      },
      { n: ["watch", "clock"], u: "231a", a: "0.6" },
      { n: ["alarm", "clock", "alarm clock"], u: "23f0", a: "0.6" },
      {
        n: [
          "00",
          "12",
          "12:00",
          "clock",
          "twelve",
          "o’clock",
          "twelve o’clock",
        ],
        u: "1f55b",
        a: "0.6",
      },
      {
        n: ["12", "12:30", "clock", "thirty", "twelve", "twelve thirty"],
        u: "1f567",
        a: "0.7",
      },
      {
        n: ["1", "00", "one", "1:00", "clock", "o’clock", "one o’clock"],
        u: "1f550",
        a: "0.6",
      },
      {
        n: ["1", "one", "1:30", "clock", "thirty", "one thirty"],
        u: "1f55c",
        a: "0.7",
      },
      {
        n: ["2", "00", "two", "2:00", "clock", "o’clock", "two o’clock"],
        u: "1f551",
        a: "0.6",
      },
      {
        n: ["2", "two", "2:30", "clock", "thirty", "two thirty"],
        u: "1f55d",
        a: "0.7",
      },
      {
        n: ["3", "00", "3:00", "clock", "three", "o’clock", "three o’clock"],
        u: "1f552",
        a: "0.6",
      },
      {
        n: ["3", "3:30", "clock", "three", "thirty", "three thirty"],
        u: "1f55e",
        a: "0.7",
      },
      {
        n: ["4", "00", "4:00", "four", "clock", "o’clock", "four o’clock"],
        u: "1f553",
        a: "0.6",
      },
      {
        n: ["4", "4:30", "four", "clock", "thirty", "four thirty"],
        u: "1f55f",
        a: "0.7",
      },
      {
        n: ["5", "00", "5:00", "five", "clock", "o’clock", "five o’clock"],
        u: "1f554",
        a: "0.6",
      },
      {
        n: ["5", "5:30", "five", "clock", "thirty", "five thirty"],
        u: "1f560",
        a: "0.7",
      },
      {
        n: ["6", "00", "six", "6:00", "clock", "o’clock", "six o’clock"],
        u: "1f555",
        a: "0.6",
      },
      {
        n: ["6", "six", "6:30", "clock", "thirty", "six thirty"],
        u: "1f561",
        a: "0.7",
      },
      {
        n: ["7", "00", "7:00", "clock", "seven", "o’clock", "seven o’clock"],
        u: "1f556",
        a: "0.6",
      },
      {
        n: ["7", "7:30", "clock", "seven", "thirty", "seven thirty"],
        u: "1f562",
        a: "0.7",
      },
      {
        n: ["8", "00", "8:00", "clock", "eight", "o’clock", "eight o’clock"],
        u: "1f557",
        a: "0.6",
      },
      {
        n: ["8", "8:30", "clock", "eight", "thirty", "eight thirty"],
        u: "1f563",
        a: "0.7",
      },
      {
        n: ["9", "00", "9:00", "nine", "clock", "o’clock", "nine o’clock"],
        u: "1f558",
        a: "0.6",
      },
      {
        n: ["9", "9:30", "nine", "clock", "thirty", "nine thirty"],
        u: "1f564",
        a: "0.7",
      },
      {
        n: ["00", "10", "ten", "10:00", "clock", "o’clock", "ten o’clock"],
        u: "1f559",
        a: "0.6",
      },
      {
        n: ["10", "ten", "10:30", "clock", "thirty", "ten thirty"],
        u: "1f565",
        a: "0.7",
      },
      {
        n: [
          "00",
          "11",
          "11:00",
          "clock",
          "eleven",
          "o’clock",
          "eleven o’clock",
        ],
        u: "1f55a",
        a: "0.6",
      },
      {
        n: ["11", "11:30", "clock", "eleven", "thirty", "eleven thirty"],
        u: "1f566",
        a: "0.7",
      },
      { n: ["dark", "moon", "new moon"], u: "1f311", a: "0.6" },
      {
        n: ["moon", "waxing", "crescent", "waxing crescent moon"],
        u: "1f312",
        a: "1",
      },
      { n: ["moon", "quarter", "first quarter moon"], u: "1f313", a: "0.6" },
      {
        n: ["moon", "waxing", "gibbous", "waxing gibbous moon"],
        u: "1f314",
        a: "0.6",
      },
      { n: ["full", "moon", "full moon"], u: "1f315", a: "0.6" },
      {
        n: ["moon", "waning", "gibbous", "waning gibbous moon"],
        u: "1f316",
        a: "1",
      },
      { n: ["moon", "quarter", "last quarter moon"], u: "1f317", a: "1" },
      {
        n: ["moon", "waning", "crescent", "waning crescent moon"],
        u: "1f318",
        a: "1",
      },
      { n: ["moon", "crescent", "crescent moon"], u: "1f319", a: "0.6" },
      { n: ["face", "moon", "new moon face"], u: "1f31a", a: "1" },
      {
        n: ["face", "moon", "quarter", "first quarter moon face"],
        u: "1f31b",
        a: "0.6",
      },
      {
        n: ["face", "moon", "quarter", "last quarter moon face"],
        u: "1f31c",
        a: "0.7",
      },
      {
        n: ["face", "full", "moon", "bright", "full moon face"],
        u: "1f31d",
        a: "1",
      },
      { n: ["sun", "face", "bright", "sun with face"], u: "1f31e", a: "1" },
      { n: ["saturn", "saturnine", "ringed planet"], u: "1fa90", a: "12" },
      { n: ["star"], u: "2b50", a: "0.6" },
      {
        n: ["glow", "star", "shining", "sparkle", "glittery", "glowing star"],
        u: "1f31f",
        a: "0.6",
      },
      {
        n: ["star", "falling", "shooting", "shooting star"],
        u: "1f320",
        a: "0.6",
      },
      { n: ["space", "milky way"], u: "1f30c", a: "0.6" },
      { n: ["sun", "cloud", "sun behind cloud"], u: "26c5", a: "0.6" },
      {
        n: ["dizzy", "cyclone", "twister", "typhoon", "hurricane"],
        u: "1f300",
        a: "0.6",
      },
      { n: ["rain", "rainbow"], u: "1f308", a: "0.6" },
      {
        n: ["rain", "clothing", "umbrella", "closed umbrella"],
        u: "1f302",
        a: "0.6",
      },
      {
        n: ["drop", "rain", "clothing", "umbrella", "umbrella with rain drops"],
        u: "2614",
        a: "0.6",
      },
      {
        n: [
          "zap",
          "danger",
          "voltage",
          "electric",
          "lightning",
          "high voltage",
        ],
        u: "26a1",
        a: "0.6",
      },
      {
        n: ["cold", "snow", "snowman", "snowman without snow"],
        u: "26c4",
        a: "0.6",
      },
      { n: ["fire", "tool", "flame"], u: "1f525", a: "0.6" },
      {
        n: ["cold", "drop", "comic", "sweat", "droplet"],
        u: "1f4a7",
        a: "0.6",
      },
      { n: ["wave", "ocean", "water", "water wave"], u: "1f30a", a: "0.6" },
    ],
    activities: [
      {
        n: ["jack", "lantern", "halloween", "celebration", "jack o lantern"],
        u: "1f383",
        a: "0.6",
      },
      {
        n: ["tree", "christmas", "celebration", "Christmas tree"],
        u: "1f384",
        a: "0.6",
      },
      { n: ["fireworks", "celebration"], u: "1f386", a: "0.6" },
      {
        n: ["sparkle", "sparkler", "fireworks", "celebration"],
        u: "1f387",
        a: "0.6",
      },
      {
        n: ["dynamite", "explosive", "fireworks", "firecracker"],
        u: "1f9e8",
        a: "11",
      },
      { n: ["*", "star", "sparkle", "sparkles"], u: "2728", a: "0.6" },
      { n: ["balloon", "celebration"], u: "1f388", a: "0.6" },
      {
        n: ["tada", "party", "popper", "celebration", "party popper"],
        u: "1f389",
        a: "0.6",
      },
      {
        n: ["ball", "confetti", "celebration", "confetti ball"],
        u: "1f38a",
        a: "0.6",
      },
      {
        n: ["tree", "banner", "japanese", "celebration", "tanabata tree"],
        u: "1f38b",
        a: "0.6",
      },
      {
        n: ["pine", "bamboo", "japanese", "celebration", "pine decoration"],
        u: "1f38d",
        a: "0.6",
      },
      {
        n: [
          "doll",
          "festival",
          "japanese",
          "celebration",
          "Japanese dolls",
          "japanese dolls",
        ],
        u: "1f38e",
        a: "0.6",
      },
      {
        n: ["carp", "streamer", "celebration", "carp streamer"],
        u: "1f38f",
        a: "0.6",
      },
      {
        n: ["bell", "wind", "chime", "wind chime", "celebration"],
        u: "1f390",
        a: "0.6",
      },
      {
        n: ["moon", "ceremony", "celebration", "moon viewing ceremony"],
        u: "1f391",
        a: "0.6",
      },
      {
        n: ["gift", "money", "hóngbāo", "lai see", "good luck", "red envelope"],
        u: "1f9e7",
        a: "11",
      },
      { n: ["ribbon", "celebration"], u: "1f380", a: "0.6" },
      {
        n: ["box", "gift", "present", "wrapped", "celebration", "wrapped gift"],
        u: "1f381",
        a: "0.6",
      },
      { n: ["ticket", "admission"], u: "1f3ab", a: "0.6" },
      { n: ["prize", "trophy"], u: "1f3c6", a: "0.6" },
      { n: ["medal", "sports medal"], u: "1f3c5", a: "1" },
      { n: ["gold", "first", "medal", "1st place medal"], u: "1f947", a: "3" },
      {
        n: ["medal", "second", "silver", "2nd place medal"],
        u: "1f948",
        a: "3",
      },
      {
        n: ["medal", "third", "bronze", "3rd place medal"],
        u: "1f949",
        a: "3",
      },
      { n: ["ball", "soccer", "football", "soccer ball"], u: "26bd", a: "0.6" },
      { n: ["ball", "baseball"], u: "26be", a: "0.6" },
      { n: ["ball", "glove", "softball", "underarm"], u: "1f94e", a: "11" },
      { n: ["ball", "hoop", "basketball"], u: "1f3c0", a: "0.6" },
      { n: ["ball", "game", "volleyball"], u: "1f3d0", a: "1" },
      {
        n: ["ball", "american", "football", "american football"],
        u: "1f3c8",
        a: "0.6",
      },
      {
        n: ["ball", "rugby", "football", "rugby football"],
        u: "1f3c9",
        a: "1",
      },
      { n: ["ball", "tennis", "racquet"], u: "1f3be", a: "0.6" },
      { n: ["ultimate", "flying disc"], u: "1f94f", a: "11" },
      { n: ["ball", "game", "bowling"], u: "1f3b3", a: "0.6" },
      { n: ["bat", "ball", "game", "cricket game"], u: "1f3cf", a: "1" },
      {
        n: ["ball", "game", "field", "stick", "hockey", "field hockey"],
        u: "1f3d1",
        a: "1",
      },
      {
        n: ["ice", "game", "puck", "stick", "hockey", "ice hockey"],
        u: "1f3d2",
        a: "1",
      },
      { n: ["ball", "goal", "stick", "lacrosse"], u: "1f94d", a: "11" },
      {
        n: ["bat", "ball", "game", "paddle", "ping pong", "table tennis"],
        u: "1f3d3",
        a: "1",
      },
      {
        n: ["game", "birdie", "racquet", "badminton", "shuttlecock"],
        u: "1f3f8",
        a: "1",
      },
      { n: ["glove", "boxing", "boxing glove"], u: "1f94a", a: "3" },
      {
        n: [
          "judo",
          "karate",
          "uniform",
          "taekwondo",
          "martial arts",
          "martial arts uniform",
        ],
        u: "1f94b",
        a: "3",
      },
      { n: ["net", "goal", "goal net"], u: "1f945", a: "3" },
      { n: ["golf", "hole", "flag in hole"], u: "26f3", a: "0.6" },
      { n: ["fish", "pole", "fishing pole"], u: "1f3a3", a: "0.6" },
      {
        n: ["scuba", "diving", "snorkeling", "diving mask"],
        u: "1f93f",
        a: "12",
      },
      {
        n: ["sash", "shirt", "running", "athletics", "running shirt"],
        u: "1f3bd",
        a: "0.6",
      },
      { n: ["ski", "skis", "snow"], u: "1f3bf", a: "0.6" },
      { n: ["sled", "sledge", "sleigh"], u: "1f6f7", a: "5" },
      { n: ["game", "rock", "curling stone"], u: "1f94c", a: "5" },
      {
        n: ["hit", "dart", "game", "target", "bullseye", "direct hit"],
        u: "1f3af",
        a: "0.6",
      },
      { n: ["toy", "yo yo", "fluctuate"], u: "1fa80", a: "12" },
      { n: ["fly", "kite", "soar"], u: "1fa81", a: "12" },
      {
        n: [
          "gun",
          "tool",
          "water",
          "pistol",
          "weapon",
          "handgun",
          "revolver",
          "water pistol",
        ],
        u: "1f52b",
        a: "0.6",
      },
      {
        n: ["8", "ball", "game", "eight", "billiard", "pool 8 ball"],
        u: "1f3b1",
        a: "0.6",
      },
      {
        n: [
          "ball",
          "tool",
          "crystal",
          "fantasy",
          "fortune",
          "fairy tale",
          "crystal ball",
        ],
        u: "1f52e",
        a: "0.6",
      },
      { n: ["magic", "witch", "wizard", "magic wand"], u: "1fa84", a: "13" },
      { n: ["game", "video game", "controller"], u: "1f3ae", a: "0.6" },
      { n: ["game", "slot", "slot machine"], u: "1f3b0", a: "0.6" },
      { n: ["die", "dice", "game", "game die"], u: "1f3b2", a: "0.6" },
      {
        n: [
          "clue",
          "piece",
          "jigsaw",
          "puzzle",
          "puzzle piece",
          "interlocking",
        ],
        u: "1f9e9",
        a: "11",
      },
      {
        n: ["toy", "plush", "stuffed", "plaything", "teddy bear"],
        u: "1f9f8",
        a: "11",
      },
      { n: ["party", "piñata", "celebration"], u: "1fa85", a: "13" },
      {
        n: ["dance", "disco", "party", "glitter", "mirror ball"],
        u: "1faa9",
        a: "14",
      },
      {
        n: ["doll", "russia", "nesting", "nesting dolls"],
        u: "1fa86",
        a: "13",
      },
      { n: ["card", "game", "joker", "wildcard"], u: "1f0cf", a: "0.6" },
      {
        n: ["red", "game", "mahjong", "mahjong red dragon"],
        u: "1f004",
        a: "0.6",
      },
      {
        n: [
          "card",
          "game",
          "flower",
          "playing",
          "japanese",
          "flower playing cards",
        ],
        u: "1f3b4",
        a: "0.6",
      },
      {
        n: [
          "art",
          "mask",
          "theater",
          "theatre",
          "performing",
          "performing arts",
        ],
        u: "1f3ad",
        a: "0.6",
      },
      {
        n: ["art", "museum", "palette", "painting", "artist palette"],
        u: "1f3a8",
        a: "0.6",
      },
      {
        n: ["spool", "thread", "needle", "sewing", "string"],
        u: "1f9f5",
        a: "11",
      },
      {
        n: [
          "needle",
          "sewing",
          "sutures",
          "stitches",
          "tailoring",
          "embroidery",
          "sewing needle",
        ],
        u: "1faa1",
        a: "13",
      },
      { n: ["yarn", "ball", "knit", "crochet"], u: "1f9f6", a: "11" },
      {
        n: ["tie", "knot", "rope", "twine", "twist", "tangled"],
        u: "1faa2",
        a: "13",
      },
    ],
    objects: [
      {
        n: ["eye", "glasses", "eyewear", "clothing", "eyeglasses"],
        u: "1f453",
        a: "0.6",
      },
      {
        n: ["goggles", "welding", "swimming", "eye protection"],
        u: "1f97d",
        a: "11",
      },
      {
        n: ["doctor", "lab coat", "scientist", "experiment"],
        u: "1f97c",
        a: "11",
      },
      {
        n: ["vest", "safety", "emergency", "safety vest"],
        u: "1f9ba",
        a: "12",
      },
      { n: ["tie", "necktie", "clothing"], u: "1f454", a: "0.6" },
      { n: ["shirt", "tshirt", "t shirt", "clothing"], u: "1f455", a: "0.6" },
      { n: ["jeans", "pants", "clothing", "trousers"], u: "1f456", a: "0.6" },
      { n: ["neck", "scarf"], u: "1f9e3", a: "5" },
      { n: ["hand", "gloves"], u: "1f9e4", a: "5" },
      { n: ["coat", "jacket"], u: "1f9e5", a: "5" },
      { n: ["socks", "stocking"], u: "1f9e6", a: "5" },
      { n: ["dress", "clothing"], u: "1f457", a: "0.6" },
      { n: ["kimono", "clothing"], u: "1f458", a: "0.6" },
      { n: ["sari", "dress", "clothing"], u: "1f97b", a: "12" },
      { n: ["bathing suit", "one piece swimsuit"], u: "1fa71", a: "12" },
      {
        n: ["briefs", "swimsuit", "one piece", "underwear", "bathing suit"],
        u: "1fa72",
        a: "12",
      },
      {
        n: ["pants", "shorts", "underwear", "bathing suit"],
        u: "1fa73",
        a: "12",
      },
      { n: ["swim", "bikini", "clothing"], u: "1f459", a: "0.6" },
      { n: ["woman", "clothing", "woman’s clothes"], u: "1f45a", a: "0.6" },
      {
        n: [
          "fan",
          "hot",
          "shy",
          "dance",
          "cooling",
          "flutter",
          "folding hand fan",
        ],
        u: "1faad",
        a: "15",
      },
      { n: ["coin", "purse", "clothing"], u: "1f45b", a: "0.6" },
      { n: ["bag", "purse", "handbag", "clothing"], u: "1f45c", a: "0.6" },
      { n: ["bag", "pouch", "clothing", "clutch bag"], u: "1f45d", a: "0.6" },
      {
        n: ["bag", "school", "satchel", "backpack", "rucksack"],
        u: "1f392",
        a: "0.6",
      },
      {
        n: [
          "zōri",
          "thongs",
          "sandals",
          "thong sandal",
          "beach sandals",
          "thong sandals",
        ],
        u: "1fa74",
        a: "13",
      },
      { n: ["man", "shoe", "clothing", "man’s shoe"], u: "1f45e", a: "0.6" },
      {
        n: ["shoe", "sneaker", "athletic", "clothing", "running shoe"],
        u: "1f45f",
        a: "0.6",
      },
      {
        n: ["boot", "hiking", "camping", "hiking boot", "backpacking"],
        u: "1f97e",
        a: "11",
      },
      {
        n: ["slip on", "slipper", "flat shoe", "ballet flat"],
        u: "1f97f",
        a: "11",
      },
      {
        n: ["heel", "shoe", "woman", "clothing", "high heeled shoe"],
        u: "1f460",
        a: "0.6",
      },
      {
        n: ["shoe", "woman", "sandal", "clothing", "woman’s sandal"],
        u: "1f461",
        a: "0.6",
      },
      { n: ["dance", "ballet", "ballet shoes"], u: "1fa70", a: "12" },
      {
        n: ["boot", "shoe", "woman", "clothing", "woman’s boot"],
        u: "1f462",
        a: "0.6",
      },
      { n: ["afro", "comb", "hair", "pick", "hair pick"], u: "1faae", a: "15" },
      { n: ["king", "crown", "queen", "clothing"], u: "1f451", a: "0.6" },
      { n: ["hat", "woman", "clothing", "woman’s hat"], u: "1f452", a: "0.6" },
      {
        n: ["hat", "top", "tophat", "top hat", "clothing"],
        u: "1f3a9",
        a: "0.6",
      },
      {
        n: [
          "cap",
          "hat",
          "clothing",
          "graduation",
          "celebration",
          "graduation cap",
        ],
        u: "1f393",
        a: "0.6",
      },
      { n: ["billed cap", "baseball cap"], u: "1f9e2", a: "5" },
      {
        n: [
          "army",
          "helmet",
          "soldier",
          "warrior",
          "military",
          "military helmet",
        ],
        u: "1fa96",
        a: "13",
      },
      {
        n: [
          "beads",
          "prayer",
          "clothing",
          "necklace",
          "religion",
          "prayer beads",
        ],
        u: "1f4ff",
        a: "1",
      },
      { n: ["makeup", "lipstick", "cosmetics"], u: "1f484", a: "0.6" },
      { n: ["ring", "diamond"], u: "1f48d", a: "0.6" },
      { n: ["gem", "jewel", "diamond", "gem stone"], u: "1f48e", a: "0.6" },
      {
        n: ["mute", "quiet", "silent", "speaker", "muted speaker"],
        u: "1f507",
        a: "1",
      },
      { n: ["soft", "speaker low volume"], u: "1f508", a: "0.7" },
      { n: ["medium", "speaker medium volume"], u: "1f509", a: "1" },
      { n: ["loud", "speaker high volume"], u: "1f50a", a: "0.6" },
      { n: ["loud", "loudspeaker", "public address"], u: "1f4e2", a: "0.6" },
      { n: ["cheering", "megaphone"], u: "1f4e3", a: "0.6" },
      { n: ["horn", "post", "postal", "postal horn"], u: "1f4ef", a: "1" },
      { n: ["bell"], u: "1f514", a: "0.6" },
      {
        n: ["bell", "mute", "quiet", "silent", "forbidden", "bell with slash"],
        u: "1f515",
        a: "1",
      },
      { n: ["music", "score", "musical score"], u: "1f3bc", a: "0.6" },
      { n: ["note", "music", "musical note"], u: "1f3b5", a: "0.6" },
      { n: ["note", "music", "notes", "musical notes"], u: "1f3b6", a: "0.6" },
      { n: ["mic", "karaoke", "microphone"], u: "1f3a4", a: "0.6" },
      { n: ["earbud", "headphone"], u: "1f3a7", a: "0.6" },
      { n: ["radio", "video"], u: "1f4fb", a: "0.6" },
      { n: ["sax", "music", "saxophone", "instrument"], u: "1f3b7", a: "0.6" },
      { n: ["accordion", "concertina", "squeeze box"], u: "1fa97", a: "13" },
      { n: ["music", "guitar", "instrument"], u: "1f3b8", a: "0.6" },
      {
        n: ["music", "piano", "keyboard", "instrument", "musical keyboard"],
        u: "1f3b9",
        a: "0.6",
      },
      { n: ["music", "trumpet", "instrument"], u: "1f3ba", a: "0.6" },
      { n: ["music", "violin", "instrument"], u: "1f3bb", a: "0.6" },
      { n: ["banjo", "music", "stringed"], u: "1fa95", a: "12" },
      { n: ["drum", "music", "drumsticks"], u: "1f941", a: "3" },
      {
        n: ["beat", "drum", "conga", "rhythm", "long drum"],
        u: "1fa98",
        a: "13",
      },
      {
        n: ["music", "shake", "rattle", "maracas", "instrument", "percussion"],
        u: "1fa87",
        a: "15",
      },
      {
        n: ["fife", "pipe", "flute", "music", "recorder", "woodwind"],
        u: "1fa88",
        a: "15",
      },
      {
        n: ["cell", "phone", "mobile", "telephone", "mobile phone"],
        u: "1f4f1",
        a: "0.6",
      },
      {
        n: [
          "cell",
          "arrow",
          "phone",
          "mobile",
          "receive",
          "mobile phone with arrow",
        ],
        u: "1f4f2",
        a: "0.6",
      },
      {
        n: ["phone", "receiver", "telephone", "telephone receiver"],
        u: "1f4de",
        a: "0.6",
      },
      { n: ["pager"], u: "1f4df", a: "0.6" },
      { n: ["fax", "fax machine"], u: "1f4e0", a: "0.6" },
      { n: ["battery"], u: "1f50b", a: "0.6" },
      { n: ["electronic", "low energy", "low battery"], u: "1faab", a: "14" },
      {
        n: ["plug", "electric", "electricity", "electric plug"],
        u: "1f50c",
        a: "0.6",
      },
      { n: ["pc", "laptop", "computer", "personal"], u: "1f4bb", a: "0.6" },
      {
        n: ["disk", "optical", "computer", "minidisk", "computer disk"],
        u: "1f4bd",
        a: "0.6",
      },
      {
        n: ["disk", "floppy", "computer", "floppy disk"],
        u: "1f4be",
        a: "0.6",
      },
      {
        n: ["cd", "disk", "optical", "computer", "optical disk"],
        u: "1f4bf",
        a: "0.6",
      },
      {
        n: ["dvd", "disk", "blu ray", "optical", "computer"],
        u: "1f4c0",
        a: "0.6",
      },
      { n: ["abacus", "calculation"], u: "1f9ee", a: "11" },
      {
        n: ["movie", "camera", "cinema", "movie camera"],
        u: "1f3a5",
        a: "0.6",
      },
      { n: ["movie", "clapper", "clapper board"], u: "1f3ac", a: "0.6" },
      { n: ["tv", "video", "television"], u: "1f4fa", a: "0.6" },
      { n: ["video", "camera"], u: "1f4f7", a: "0.6" },
      {
        n: ["flash", "video", "camera", "camera with flash"],
        u: "1f4f8",
        a: "1",
      },
      { n: ["video", "camera", "video camera"], u: "1f4f9", a: "0.6" },
      { n: ["vhs", "tape", "video", "videocassette"], u: "1f4fc", a: "0.6" },
      {
        n: [
          "tool",
          "glass",
          "search",
          "magnifying",
          "magnifying glass tilted left",
        ],
        u: "1f50d",
        a: "0.6",
      },
      {
        n: [
          "tool",
          "glass",
          "search",
          "magnifying",
          "magnifying glass tilted right",
        ],
        u: "1f50e",
        a: "0.6",
      },
      {
        n: ["bulb", "idea", "comic", "light", "electric", "light bulb"],
        u: "1f4a1",
        a: "0.6",
      },
      {
        n: ["tool", "light", "torch", "electric", "flashlight"],
        u: "1f526",
        a: "0.6",
      },
      {
        n: ["bar", "red", "light", "lantern", "red paper lantern"],
        u: "1f3ee",
        a: "0.6",
      },
      { n: ["oil", "diya", "lamp", "diya lamp"], u: "1fa94", a: "12" },
      {
        n: [
          "book",
          "cover",
          "notebook",
          "decorated",
          "notebook with decorative cover",
        ],
        u: "1f4d4",
        a: "0.6",
      },
      { n: ["book", "closed", "closed book"], u: "1f4d5", a: "0.6" },
      { n: ["book", "open", "open book"], u: "1f4d6", a: "0.6" },
      { n: ["book", "green", "green book"], u: "1f4d7", a: "0.6" },
      { n: ["blue", "book", "blue book"], u: "1f4d8", a: "0.6" },
      { n: ["book", "orange", "orange book"], u: "1f4d9", a: "0.6" },
      { n: ["book", "books"], u: "1f4da", a: "0.6" },
      { n: ["notebook"], u: "1f4d3", a: "0.6" },
      { n: ["ledger", "notebook"], u: "1f4d2", a: "0.6" },
      {
        n: ["curl", "page", "document", "page with curl"],
        u: "1f4c3",
        a: "0.6",
      },
      { n: ["paper", "scroll"], u: "1f4dc", a: "0.6" },
      { n: ["page", "document", "page facing up"], u: "1f4c4", a: "0.6" },
      { n: ["news", "paper", "newspaper"], u: "1f4f0", a: "0.6" },
      {
        n: ["mark", "tabs", "marker", "bookmark", "bookmark tabs"],
        u: "1f4d1",
        a: "0.6",
      },
      { n: ["mark", "bookmark"], u: "1f516", a: "0.6" },
      {
        n: ["bag", "money", "dollar", "moneybag", "money bag"],
        u: "1f4b0",
        a: "0.6",
      },
      {
        n: ["coin", "gold", "metal", "money", "silver", "treasure"],
        u: "1fa99",
        a: "13",
      },
      {
        n: [
          "yen",
          "bill",
          "note",
          "money",
          "banknote",
          "currency",
          "yen banknote",
        ],
        u: "1f4b4",
        a: "0.6",
      },
      {
        n: [
          "bill",
          "note",
          "money",
          "dollar",
          "banknote",
          "currency",
          "dollar banknote",
        ],
        u: "1f4b5",
        a: "0.6",
      },
      {
        n: [
          "bill",
          "euro",
          "note",
          "money",
          "banknote",
          "currency",
          "euro banknote",
        ],
        u: "1f4b6",
        a: "1",
      },
      {
        n: [
          "bill",
          "note",
          "money",
          "pound",
          "banknote",
          "currency",
          "pound banknote",
        ],
        u: "1f4b7",
        a: "1",
      },
      {
        n: ["fly", "bill", "money", "wings", "banknote", "money with wings"],
        u: "1f4b8",
        a: "0.6",
      },
      { n: ["card", "money", "credit", "credit card"], u: "1f4b3", a: "0.6" },
      {
        n: ["proof", "receipt", "evidence", "accounting", "bookkeeping"],
        u: "1f9fe",
        a: "11",
      },
      {
        n: [
          "yen",
          "chart",
          "graph",
          "money",
          "growth",
          "chart increasing with yen",
        ],
        u: "1f4b9",
        a: "0.6",
      },
      { n: ["mail", "email", "e mail", "letter"], u: "1f4e7", a: "0.6" },
      {
        n: [
          "email",
          "e mail",
          "letter",
          "receive",
          "envelope",
          "incoming",
          "incoming envelope",
        ],
        u: "1f4e8",
        a: "0.6",
      },
      {
        n: [
          "arrow",
          "email",
          "e mail",
          "envelope",
          "outgoing",
          "envelope with arrow",
        ],
        u: "1f4e9",
        a: "0.6",
      },
      {
        n: ["box", "mail", "sent", "tray", "letter", "outbox", "outbox tray"],
        u: "1f4e4",
        a: "0.6",
      },
      {
        n: ["box", "mail", "tray", "inbox", "letter", "receive", "inbox tray"],
        u: "1f4e5",
        a: "0.6",
      },
      { n: ["box", "parcel", "package"], u: "1f4e6", a: "0.6" },
      {
        n: [
          "mail",
          "closed",
          "mailbox",
          "postbox",
          "closed mailbox with raised flag",
        ],
        u: "1f4eb",
        a: "0.6",
      },
      {
        n: [
          "mail",
          "closed",
          "lowered",
          "mailbox",
          "postbox",
          "closed mailbox with lowered flag",
        ],
        u: "1f4ea",
        a: "0.6",
      },
      {
        n: [
          "mail",
          "open",
          "mailbox",
          "postbox",
          "open mailbox with raised flag",
        ],
        u: "1f4ec",
        a: "0.7",
      },
      {
        n: [
          "mail",
          "open",
          "lowered",
          "mailbox",
          "postbox",
          "open mailbox with lowered flag",
        ],
        u: "1f4ed",
        a: "0.7",
      },
      { n: ["mail", "postbox", "mailbox"], u: "1f4ee", a: "0.6" },
      { n: ["memo", "pencil"], u: "1f4dd", a: "0.6" },
      { n: ["briefcase"], u: "1f4bc", a: "0.6" },
      { n: ["file", "folder", "file folder"], u: "1f4c1", a: "0.6" },
      {
        n: ["file", "open", "folder", "open file folder"],
        u: "1f4c2",
        a: "0.6",
      },
      { n: ["date", "calendar"], u: "1f4c5", a: "0.6" },
      { n: ["calendar", "tear off calendar"], u: "1f4c6", a: "0.6" },
      { n: ["card", "index", "rolodex", "card index"], u: "1f4c7", a: "0.6" },
      {
        n: ["chart", "graph", "trend", "growth", "upward", "chart increasing"],
        u: "1f4c8",
        a: "0.6",
      },
      {
        n: ["down", "chart", "graph", "trend", "chart decreasing"],
        u: "1f4c9",
        a: "0.6",
      },
      { n: ["bar", "chart", "graph", "bar chart"], u: "1f4ca", a: "0.6" },
      { n: ["clipboard"], u: "1f4cb", a: "0.6" },
      { n: ["pin", "pushpin"], u: "1f4cc", a: "0.6" },
      { n: ["pin", "pushpin", "round pushpin"], u: "1f4cd", a: "0.6" },
      { n: ["paperclip"], u: "1f4ce", a: "0.6" },
      { n: ["ruler", "straight edge", "straight ruler"], u: "1f4cf", a: "0.6" },
      {
        n: ["set", "ruler", "triangle", "triangular ruler"],
        u: "1f4d0",
        a: "0.6",
      },
      { n: ["locked", "closed"], u: "1f512", a: "0.6" },
      { n: ["lock", "open", "unlock", "unlocked"], u: "1f513", a: "0.6" },
      {
        n: ["ink", "nib", "pen", "lock", "privacy", "locked with pen"],
        u: "1f50f",
        a: "0.6",
      },
      {
        n: ["key", "lock", "closed", "secure", "locked with key"],
        u: "1f510",
        a: "0.6",
      },
      { n: ["key", "lock", "password"], u: "1f511", a: "0.6" },
      { n: ["tool", "hammer"], u: "1f528", a: "0.6" },
      { n: ["axe", "chop", "wood", "split", "hatchet"], u: "1fa93", a: "12" },
      { n: ["bomb", "comic"], u: "1f4a3", a: "0.6" },
      { n: ["rebound", "boomerang", "repercussion"], u: "1fa83", a: "13" },
      {
        n: ["bow", "arrow", "archer", "zodiac", "sagittarius", "bow and arrow"],
        u: "1f3f9",
        a: "1",
      },
      {
        n: ["saw", "tool", "lumber", "carpenter", "carpentry saw"],
        u: "1fa9a",
        a: "13",
      },
      { n: ["tool", "wrench", "spanner"], u: "1f527", a: "0.6" },
      { n: ["tool", "screw", "screwdriver"], u: "1fa9b", a: "13" },
      { n: ["nut", "bolt", "tool", "nut and bolt"], u: "1f529", a: "0.6" },
      { n: ["blind", "white cane", "accessibility"], u: "1f9af", a: "12" },
      { n: ["link"], u: "1f517", a: "0.6" },
      {
        n: ["break", "chain", "cuffs", "freedom", "breaking", "broken chain"],
        u: "26d3-fe0f-200d-1f4a5",
        a: "15.1",
      },
      {
        n: ["hook", "catch", "crook", "curve", "ensnare", "selling point"],
        u: "1fa9d",
        a: "13",
      },
      { n: ["tool", "chest", "toolbox", "mechanic"], u: "1f9f0", a: "11" },
      {
        n: ["magnet", "magnetic", "horseshoe", "attraction"],
        u: "1f9f2",
        a: "11",
      },
      { n: ["rung", "step", "climb", "ladder"], u: "1fa9c", a: "13" },
      {
        n: [
          "lab",
          "chemist",
          "science",
          "test tube",
          "chemistry",
          "experiment",
        ],
        u: "1f9ea",
        a: "11",
      },
      {
        n: ["lab", "biology", "culture", "bacteria", "biologist", "petri dish"],
        u: "1f9eb",
        a: "11",
      },
      {
        n: ["dna", "gene", "life", "genetics", "biologist", "evolution"],
        u: "1f9ec",
        a: "11",
      },
      { n: ["tool", "science", "microscope"], u: "1f52c", a: "1" },
      { n: ["tool", "science", "telescope"], u: "1f52d", a: "1" },
      {
        n: ["dish", "antenna", "satellite", "satellite antenna"],
        u: "1f4e1",
        a: "0.6",
      },
      {
        n: ["shot", "sick", "needle", "syringe", "medicine"],
        u: "1f489",
        a: "0.6",
      },
      {
        n: [
          "bleed",
          "injury",
          "medicine",
          "menstruation",
          "drop of blood",
          "blood donation",
        ],
        u: "1fa78",
        a: "12",
      },
      { n: ["pill", "sick", "doctor", "medicine"], u: "1f48a", a: "0.6" },
      { n: ["bandage", "adhesive bandage"], u: "1fa79", a: "12" },
      {
        n: ["cane", "hurt", "stick", "crutch", "disability", "mobility aid"],
        u: "1fa7c",
        a: "14",
      },
      {
        n: ["heart", "doctor", "medicine", "stethoscope"],
        u: "1fa7a",
        a: "12",
      },
      {
        n: ["x ray", "bones", "doctor", "medical", "skeleton"],
        u: "1fa7b",
        a: "14",
      },
      { n: ["door"], u: "1f6aa", a: "0.6" },
      {
        n: ["lift", "hoist", "elevator", "accessibility"],
        u: "1f6d7",
        a: "13",
      },
      {
        n: ["mirror", "speculum", "reflector", "reflection"],
        u: "1fa9e",
        a: "13",
      },
      {
        n: ["view", "frame", "window", "opening", "fresh air", "transparent"],
        u: "1fa9f",
        a: "13",
      },
      { n: ["sit", "seat", "chair"], u: "1fa91", a: "12" },
      { n: ["toilet"], u: "1f6bd", a: "0.6" },
      {
        n: ["toilet", "plunger", "plumber", "suction", "force cup"],
        u: "1faa0",
        a: "13",
      },
      { n: ["water", "shower"], u: "1f6bf", a: "1" },
      { n: ["bath", "bathtub"], u: "1f6c1", a: "1" },
      {
        n: ["bait", "trap", "snare", "mousetrap", "mouse trap"],
        u: "1faa4",
        a: "13",
      },
      { n: ["razor", "sharp", "shave"], u: "1fa92", a: "12" },
      {
        n: ["lotion", "shampoo", "sunscreen", "moisturizer", "lotion bottle"],
        u: "1f9f4",
        a: "11",
      },
      { n: ["diaper", "punk rock", "safety pin"], u: "1f9f7", a: "11" },
      { n: ["broom", "witch", "cleaning", "sweeping"], u: "1f9f9", a: "11" },
      { n: ["basket", "picnic", "farming", "laundry"], u: "1f9fa", a: "11" },
      {
        n: ["paper towels", "toilet paper", "roll of paper"],
        u: "1f9fb",
        a: "11",
      },
      { n: ["vat", "cask", "pail", "bucket"], u: "1faa3", a: "13" },
      {
        n: ["bar", "soap", "lather", "bathing", "cleaning", "soapdish"],
        u: "1f9fc",
        a: "11",
      },
      {
        n: ["burp", "soap", "clean", "bubbles", "underwater"],
        u: "1fae7",
        a: "14",
      },
      {
        n: [
          "brush",
          "clean",
          "teeth",
          "dental",
          "hygiene",
          "bathroom",
          "toothbrush",
        ],
        u: "1faa5",
        a: "13",
      },
      { n: ["sponge", "porous", "cleaning", "absorbing"], u: "1f9fd", a: "11" },
      {
        n: ["fire", "quench", "extinguish", "fire extinguisher"],
        u: "1f9ef",
        a: "11",
      },
      {
        n: ["cart", "trolley", "shopping", "shopping cart"],
        u: "1f6d2",
        a: "3",
      },
      { n: ["smoking", "cigarette"], u: "1f6ac", a: "0.6" },
      {
        n: ["grave", "cemetery", "headstone", "graveyard", "tombstone"],
        u: "1faa6",
        a: "13",
      },
      {
        n: ["bead", "charm", "nazar", "evil eye", "talisman", "nazar amulet"],
        u: "1f9ff",
        a: "11",
      },
      {
        n: [
          "hand",
          "mary",
          "hamsa",
          "amulet",
          "fatima",
          "miriam",
          "protection",
        ],
        u: "1faac",
        a: "14",
      },
      { n: ["moai", "face", "moyai", "statue"], u: "1f5ff", a: "0.6" },
      {
        n: ["sign", "picket", "placard", "protest", "demonstration"],
        u: "1faa7",
        a: "13",
      },
      {
        n: ["id", "license", "security", "credentials", "identification card"],
        u: "1faaa",
        a: "14",
      },
    ],
    symbols: [
      {
        n: ["atm", "bank", "teller", "ATM sign", "atm sign", "automated"],
        u: "1f3e7",
        a: "0.6",
      },
      { n: ["litter", "litter bin", "litter in bin sign"], u: "1f6ae", a: "1" },
      {
        n: ["water", "potable", "drinking", "potable water"],
        u: "1f6b0",
        a: "1",
      },
      { n: ["access", "wheelchair symbol"], u: "267f", a: "0.6" },
      {
        n: [
          "wc",
          "man",
          "toilet",
          "bathroom",
          "lavatory",
          "restroom",
          "men’s room",
        ],
        u: "1f6b9",
        a: "0.6",
      },
      {
        n: [
          "wc",
          "woman",
          "toilet",
          "bathroom",
          "lavatory",
          "restroom",
          "women’s room",
        ],
        u: "1f6ba",
        a: "0.6",
      },
      {
        n: ["wc", "toilet", "restroom", "bathroom", "lavatory"],
        u: "1f6bb",
        a: "0.6",
      },
      { n: ["baby", "changing", "baby symbol"], u: "1f6bc", a: "0.6" },
      {
        n: [
          "wc",
          "water",
          "closet",
          "toilet",
          "bathroom",
          "lavatory",
          "restroom",
          "water closet",
        ],
        u: "1f6be",
        a: "0.6",
      },
      { n: ["control", "passport", "passport control"], u: "1f6c2", a: "1" },
      { n: ["customs"], u: "1f6c3", a: "1" },
      { n: ["claim", "baggage", "baggage claim"], u: "1f6c4", a: "1" },
      {
        n: ["locker", "baggage", "luggage", "left luggage"],
        u: "1f6c5",
        a: "1",
      },
      {
        n: ["child", "traffic", "crossing", "pedestrian", "children crossing"],
        u: "1f6b8",
        a: "1",
      },
      {
        n: [
          "no",
          "not",
          "entry",
          "traffic",
          "no entry",
          "forbidden",
          "prohibited",
        ],
        u: "26d4",
        a: "0.6",
      },
      {
        n: ["no", "not", "entry", "forbidden", "prohibited"],
        u: "1f6ab",
        a: "0.6",
      },
      {
        n: ["no", "bike", "bicycle", "forbidden", "prohibited", "no bicycles"],
        u: "1f6b3",
        a: "1",
      },
      {
        n: ["no", "not", "smoking", "forbidden", "no smoking", "prohibited"],
        u: "1f6ad",
        a: "0.6",
      },
      {
        n: ["no", "not", "litter", "forbidden", "prohibited", "no littering"],
        u: "1f6af",
        a: "1",
      },
      {
        n: ["water", "non potable", "non drinking", "non potable water"],
        u: "1f6b1",
        a: "1",
      },
      {
        n: [
          "no",
          "not",
          "forbidden",
          "pedestrian",
          "prohibited",
          "no pedestrians",
        ],
        u: "1f6b7",
        a: "1",
      },
      {
        n: ["no", "cell", "phone", "mobile", "forbidden", "no mobile phones"],
        u: "1f4f5",
        a: "1",
      },
      {
        n: [
          "18",
          "eighteen",
          "underage",
          "prohibited",
          "age restriction",
          "no one under eighteen",
        ],
        u: "1f51e",
        a: "0.6",
      },
      {
        n: ["arrow", "reload", "clockwise", "clockwise vertical arrows"],
        u: "1f503",
        a: "0.6",
      },
      {
        n: [
          "arrow",
          "withershins",
          "anticlockwise",
          "counterclockwise",
          "counterclockwise arrows button",
        ],
        u: "1f504",
        a: "1",
      },
      { n: ["back", "arrow", "BACK arrow"], u: "1f519", a: "0.6" },
      { n: ["end", "arrow", "END arrow"], u: "1f51a", a: "0.6" },
      { n: ["on", "on!", "mark", "arrow", "ON! arrow"], u: "1f51b", a: "0.6" },
      { n: ["soon", "arrow", "SOON arrow"], u: "1f51c", a: "0.6" },
      { n: ["up", "top", "arrow", "TOP arrow"], u: "1f51d", a: "0.6" },
      { n: ["worship", "religion", "place of worship"], u: "1f6d0", a: "1" },
      {
        n: ["menorah", "religion", "candelabrum", "candlestick"],
        u: "1f54e",
        a: "1",
      },
      {
        n: ["star", "fortune", "dotted six pointed star"],
        u: "1f52f",
        a: "0.6",
      },
      { n: ["sikh", "khanda", "religion"], u: "1faaf", a: "15" },
      { n: ["ram", "Aries", "aries", "zodiac"], u: "2648", a: "0.6" },
      { n: ["ox", "bull", "Taurus", "taurus", "zodiac"], u: "2649", a: "0.6" },
      { n: ["twins", "Gemini", "gemini", "zodiac"], u: "264a", a: "0.6" },
      { n: ["crab", "Cancer", "cancer", "zodiac"], u: "264b", a: "0.6" },
      { n: ["Leo", "leo", "lion", "zodiac"], u: "264c", a: "0.6" },
      { n: ["Virgo", "virgo", "zodiac"], u: "264d", a: "0.6" },
      {
        n: ["Libra", "libra", "scales", "zodiac", "balance", "justice"],
        u: "264e",
        a: "0.6",
      },
      {
        n: ["zodiac", "Scorpio", "scorpio", "scorpion", "scorpius"],
        u: "264f",
        a: "0.6",
      },
      {
        n: ["archer", "zodiac", "Sagittarius", "sagittarius"],
        u: "2650",
        a: "0.6",
      },
      { n: ["goat", "zodiac", "Capricorn", "capricorn"], u: "2651", a: "0.6" },
      {
        n: ["water", "bearer", "zodiac", "Aquarius", "aquarius"],
        u: "2652",
        a: "0.6",
      },
      { n: ["fish", "Pisces", "pisces", "zodiac"], u: "2653", a: "0.6" },
      {
        n: ["snake", "bearer", "zodiac", "serpent", "Ophiuchus", "ophiuchus"],
        u: "26ce",
        a: "0.6",
      },
      { n: ["arrow", "crossed", "shuffle tracks button"], u: "1f500", a: "1" },
      {
        n: ["arrow", "repeat", "clockwise", "repeat button"],
        u: "1f501",
        a: "1",
      },
      {
        n: ["once", "arrow", "clockwise", "repeat single button"],
        u: "1f502",
        a: "1",
      },
      {
        n: ["fast", "arrow", "double", "forward", "fast forward button"],
        u: "23e9",
        a: "0.6",
      },
      {
        n: ["arrow", "double", "rewind", "fast reverse button"],
        u: "23ea",
        a: "0.6",
      },
      { n: ["arrow", "button", "upwards button"], u: "1f53c", a: "0.6" },
      { n: ["arrow", "double", "fast up button"], u: "23eb", a: "0.6" },
      {
        n: ["down", "arrow", "button", "downwards button"],
        u: "1f53d",
        a: "0.6",
      },
      {
        n: ["down", "arrow", "double", "fast down button"],
        u: "23ec",
        a: "0.6",
      },
      { n: ["film", "movie", "cinema", "camera"], u: "1f3a6", a: "0.6" },
      { n: ["dim", "low", "dim button", "brightness"], u: "1f505", a: "1" },
      { n: ["bright", "brightness", "bright button"], u: "1f506", a: "1" },
      {
        n: ["bar", "cell", "phone", "mobile", "antenna", "antenna bars"],
        u: "1f4f6",
        a: "0.6",
      },
      {
        n: ["wifi", "wi fi", "network", "wireless", "computer", "internet"],
        u: "1f6dc",
        a: "15",
      },
      {
        n: [
          "cell",
          "mode",
          "phone",
          "mobile",
          "telephone",
          "vibration",
          "vibration mode",
        ],
        u: "1f4f3",
        a: "0.6",
      },
      {
        n: ["off", "cell", "phone", "mobile", "telephone", "mobile phone off"],
        u: "1f4f4",
        a: "0.6",
      },
      { n: ["+", "plus", "math", "sign"], u: "2795", a: "0.6" },
      { n: [" ", "−", "math", "sign", "minus"], u: "2796", a: "0.6" },
      { n: ["÷", "math", "sign", "divide", "division"], u: "2797", a: "0.6" },
      { n: ["math", "equality", "heavy equals sign"], u: "1f7f0", a: "14" },
      {
        n: ["?", "mark", "question", "punctuation", "red question mark"],
        u: "2753",
        a: "0.6",
      },
      {
        n: [
          "?",
          "mark",
          "outlined",
          "question",
          "punctuation",
          "white question mark",
        ],
        u: "2754",
        a: "0.6",
      },
      {
        n: [
          "!",
          "mark",
          "outlined",
          "exclamation",
          "punctuation",
          "white exclamation mark",
        ],
        u: "2755",
        a: "0.6",
      },
      {
        n: ["!", "mark", "exclamation", "punctuation", "red exclamation mark"],
        u: "2757",
        a: "0.6",
      },
      {
        n: ["bank", "money", "currency", "exchange", "currency exchange"],
        u: "1f4b1",
        a: "0.6",
      },
      {
        n: ["money", "dollar", "currency", "heavy dollar sign"],
        u: "1f4b2",
        a: "0.6",
      },
      {
        n: ["ship", "tool", "anchor", "emblem", "trident", "trident emblem"],
        u: "1f531",
        a: "0.6",
      },
      { n: ["name", "badge", "name badge"], u: "1f4db", a: "0.6" },
      {
        n: [
          "leaf",
          "chevron",
          "beginner",
          "japanese",
          "Japanese symbol for beginner",
          "japanese symbol for beginner",
        ],
        u: "1f530",
        a: "0.6",
      },
      {
        n: ["o", "red", "large", "circle", "hollow red circle"],
        u: "2b55",
        a: "0.6",
      },
      {
        n: ["✓", "mark", "check", "button", "check mark button"],
        u: "2705",
        a: "0.6",
      },
      {